[package]
name = "tanks"
version = "0.1.0"
edition = "2018"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[features]
visible = ["arcana/visible"]
client = ["arcana/client"]
server = ["arcana/server"]

[dependencies]
alkahest = { version = "0.1", features = ["nightly"] }
arcana = { path = "../..", features = ["physics2d"], default-features = false }
goods = { version = "0.11.1" }
color-eyre = "0.5"
eyre = "0.6"
futures = "0.3"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
tracing = "0.1"
ordered-float = "2.1"
thiserror = "1.0"
