
[workspace]
members = [
    "engine",
    "physics",
    "tiles",
    "examples/blocks",
    # "examples/tanks",
    # "examples/tanks/client",
    # "examples/tanks/server",
    "examples/bunnymark",
    # "examples/gltf-test",
    # "examples/unfold"
]

[profile.release]
panic = "abort"
