
[workspace]
members = [
    "engine",
    "examples/blocks",
    "examples/tanks/client",
    "examples/tanks/server",
    "examples/bunnymark",
    "examples/gltf-test",
    "examples/unfold"
]

[profile.release]
panic = "abort"
