[package]
name = "untitled"
version = "0.1.0"
edition = "2021"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arcana = { path = "../../engine", features = ["3d"] }
color-eyre = "0.6"
