[package]
name = "blocks"
version = "0.1.0"
edition = "2018"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arcana = { path = "../..", features = ["physics2d"] }
color-eyre = "0.5"
eyre = "0.6"
futures = "0.3"
rand = "0.8"
