[package]
name = "arcana-time"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2021"


[features]
std = []
default = ["std"]

[dependencies]
serde = { version = "1.0", optional = true }
