[package]
name = "gltf-test"
version = "0.1.0"
edition = "2021"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arcana = { path = "../../engine", features = ["graphics", "3d", "asset-pipeline"] }
color-eyre = "0.6"
