[package]
name = "gltf-test"
version = "0.1.0"
edition = "2018"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arcana = { path = "../.." }
color-eyre = "0.5"
