[package]
name = "unfold"
version = "0.1.0"
edition = "2021"
authors = ["Zakarum <zakarumych@ya.ru>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arcana = { path = "../..", features = ["2d", "visible", "graphics", "treasury"] }
tracing = "0.1"
goods = { path = "../../../goods" }
